name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checkout the code
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Install dependencies
      - name: Install Dependencies
        run: |
          npm install

      # Build hostedPages app
      - name: Build hostedPages
        run: |
          npx ng build hostedPages --output-path=dist/hostedPages

      # Build profile app
      - name: Build profile
        run: |
          npx ng build profile --output-path=dist/profile

      # List files in dist/hostedPages and dist/profile for debugging
      - name: List files in dist/hostedPages
        run: |
          echo "Listing files in dist/hostedPages"
          ls -R dist/hostedPages

      - name: List files in dist/profile
        run: |
          echo "Listing files in dist/profile"
          ls -R dist/profile

      # Create dist/app directory and move the files
      - name: Merge Output Directories
        run: |
          # Create a single dist directory for the merged files
          mkdir -p dist/app
          mkdir -p dist/app/profile
          
          # Move the hostedPages browser files into dist/app
          mv dist/hostedPages/browser/* dist/app/
          
          # Move the profile browser files into dist/app/profile
          mv dist/profile/browser/* dist/app/profile/

      # List files in dist/app for debugging
      - name: List files in dist/app
        run: |
          echo "Listing files in dist/app"
          ls -R dist/app

      # Verify that the 'index.html' file is in the 'dist/app' directory
      - name: Verify index.html exists
        run: |
          if [ ! -f dist/app/index.html ]; then
            echo "index.html not found in dist/app"
            exit 1
          fi

      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_MUSHROOM_07619590 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: "upload"
          app_location: "dist/app"  # This is where the merged build outputs should be
          api_location: ""  # Leave empty since you don't have an API
          output_location: ""  # Leave empty since output is in app_location

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_MUSHROOM_07619590 }}
          action: "close"
